pipeline {
    agent any
    stages {
        stage('Build & Test') {
            steps {
                sh 'docker compose down -v --remove-orphans || true'
                sh 'docker compose up --build -d'
                sh 'sleep 12'
                sh 'curl -f http://localhost || exit 1'
                sh 'curl -f http://localhost:3000/posts || exit 1'
                echo 'BLOGUS marche parfaitement !'
            }
            post { always { sh 'docker compose down -v' } }
        }
    }
}
